### ISSUE TITLE
idl publish fails with ENOENT

### ISSUE THREAD

**Issue by blampe** [uber/idl#42]
Looks like we're getting an error when trying to read from cache?

```
idl publish --repository=... --cacheDir=/.../.idl --
ERR: Error: ENOENT, readdir '/...'
```

**Comment by malandrew** [comment]
How do I reproduce this?

**Comment by blampe** [comment]
Check the Jenkins job running this.

**Comment by malandrew** [comment]
Got the alert on Friday. Been talking to Vytenis about this already since it was broken by a change he made to pdebuilder. I believe he fixed it yesterday and I saw a notice that said it was working again, but I haven't had a chance to double check yet. Will do when I get home later today.

Andrew

**Comment by blampe** [comment]
I think you're talking about something else.

**Comment by malandrew** [comment]
Oh, is this the failed publish jobs in jenkins that fail with ENOENT? If so, that's not an issue with IDL, but an issue with the fact that the herald rules aren't powerful/flexible enough to determine if a repo is publishable. The Herald Rule catches a lot of false positives.

**Comment by malandrew** [comment]
Yup, I just checked two ENOENT ones and that is exactly the case. This is expected behavior.

**Comment by malandrew** [comment]
So, I thought more about this and while 99% of the failed tests in jenkins are false positives, there is the rare repo that should be published but was not. Almost all of theses are because the thrift files are in the wrong path. Instead of being in `idl/github.com/foo/bar/*.thrift`, some people in the past have put the file in `idl/github.com/foo/bar/thrift/*.thrift`. This once common mistake however was the result of a small bug in the migration script in the idl wiki that has since been fixed.

With this in mind, I could make the error a bit more descriptive like "No *.thrift files found in ./idl/github.com/foo/bar", but I kind of assume that everyone using idl that sees this error is familiar with the meaningof an ENOENT error message.  

This could be a nice little interface change, but I'd say #23, #30 and #44 are greater priority.
